#!/bin/bash

extractEnvVars() {
  if [[ $API_ADDRESS == "" ]] && [[ $VAULT_SERVER_MODE == "development" ]];
     API_ADDRESS="http://localhost:3000"
  fi
}

if [[ "$1" == "server" ]]; then
  extractEnvVars

  envsubst < /vault/template.hcl > /vault/config/main.hcl


  /usr/local/bin/docker-entrypoint.sh
else
  exec "$@"
fi

